version: '3.9'

services:
  app:
    container_name: demo_app
    build:
      context: ./
      dockerfile: docker-compose/app/Dockerfile
    command: [ "java", "-Xdebug", "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "./application.jar" ]
    ports:
      - 8080:8080
      - 5005:5005
    networks: [ javademo-network ]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: demo_postgres
    image: "postgres:15.5"
    env_file:
      - ./docker-compose/postgres/variables.env
    ports:
      - 5432:5432
    volumes:
      - javademo-app-db:/var/lib/postgresql/data
    networks: [ javademo-network ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  javademo-app-db:

networks:
  javademo-network:
