CREATE SCHEMA COMPANY;

CREATE TABLE COMPANY.DEPARTMENT (
    ID uuid DEFAULT random_uuid() PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    UNIQUE (NAME)
);

CREATE TABLE COMPANY.EMPLOYEE (
    ID uuid DEFAULT random_uuid() PRIMARY KEY,
    DEPARTMENT_ID uuid NOT NULL,
    FIRST_NAME VARCHAR NOT NULL,
    LAST_NAME VARCHAR NOT NULL,
    SALARY DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES COMPANY.DEPARTMENT(ID)
);
