spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/demodb
    username: postgres
    password: postgrespassword
  jpa:
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

