spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/demodb
    username: postgres
    password: postgrespassword

