CREATE SCHEMA COMPANY;

CREATE TABLE COMPANY.DEPARTMENT (
    ID uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    NAME VARCHAR UNIQUE NOT NULL
);

CREATE TABLE COMPANY.EMPLOYEE (
    ID uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    DEPARTMENT_ID uuid NOT NULL,
    FIRST_NAME VARCHAR NOT NULL,
    LAST_NAME VARCHAR NOT NULL,
    SALARY DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_department FOREIGN KEY (DEPARTMENT_ID) REFERENCES COMPANY.DEPARTMENT(ID)
);
